### ISSUE TITLE
Asset Compilation on Remote Hosts

### ISSUE THREAD

**Issue by wedtm** [reflection/designmodo-flatuipro-rails#13]
When deploying to remote hosts (i.e. Heroku) the Flat UI Pro source files are not available for inclusion during compliation. This leads to the asset compilation failing out with a file not found error.

What is the recommended work around for this?

**Comment by reflection** [comment]
The solution is to precompile your assets, then push up to Heroku.  Worked for me when testing.  Let me know if you have issues with this.
