### ISSUE TITLE
Travis-CI tests fail from this gem 

### ISSUE THREAD

**Issue by akshatpradhan** [reflection/designmodo-flatuipro-rails#15]
I keep getting this error from Travis-CI and I really think its because Travis can't find the flat ui assets. 

https://travis-ci.org/akshatpradhan/spoutlets/builds/11513504

By looking at the errors above, can you tell me if this is true?

**Comment by reflection** [comment]
Your build errors don't mention the _designmodo-flatuipro-rails_ gem.  Looks like a problem when compiling native extensions for the debugger gem?

``` bash
Installing debugger (1.6.0) 
Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.
    /home/travis/.rvm/rubies/ruby-1.9.3-p448/bin/ruby extconf.rb 
checking for rb_method_entry_t.called_id in method.h... no
checking for rb_control_frame_t.method_id in method.h... no
checking for rb_method_entry_t.called_id in method.h... no
checking for rb_control_frame_t.method_id in method.h... no
Makefile creation failed
**************************************************************************
No source for ruby-1.9.3-p448 provided with debugger-ruby_core_source gem.
**************************************************************************
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.
```

Perhaps you didn't install the header files for ruby?  On Ubuntu I think a simple 'apt-get install ruby-dev' will do the trick (and of course you probably need gcc/g++).

**Comment by akshatpradhan** [comment]
You're right actually. It was a completely separate issue not related to this. The reason that was happening was because of bad configuration settings in .travis.yml and an inclusion of debugger gems that Travis told me I shouldn't have included in the first place. Thank you!
