### ISSUE TITLE
Flat UI Pro Directory

### ISSUE THREAD

**Issue by theHerb** [reflection/designmodo-flatuipro-rails#2]
I keep getting "Invalid Flat UI Pro Directory"

Command:
rails generate flatuipro:install ~/code/designmodo/Flat-UI-Pro/

NOTE: I've only copied the UI directory from the download to the directory ~/code/designmodo/Flat-UI-Pro/

**Comment by reflection** [comment]
Unfortunately the gem doesn't detect your case correctly.  I'll fix this when Flat UI Pro 1.2 comes out.

For now, point it to the root Flat UI Pro directory (i.e. the UI directory would be in ~/code/designmodo/Flat-UI-Pro/HTML/UI in your case)

**Comment by reflection** [comment]
Oh and you would use the same command

``` bash
rails generate flatuipro:install ~/code/designmodo/Flat-UI-Pro/
```

**Comment by weavermedia** [comment]
I was getting the same error when I used path starting with ~/ like this:

<pre>rails generate flatuipro:install "~/Dropbox/Developer/Flat UI HTML - Personal License"</pre>

Referencing it from the drive root seems to have worked though:

<pre>rails generate flatuipro:install "/Users/danielweaver/dropbox/developer/Flat UI HTML - Personal License"</pre>
