### ISSUE TITLE
Could not find 'flat-ui.css' in any of your source paths while generating Flat UI Pro in rails app

### ISSUE THREAD

**Issue by rhtprwl** [reflection/designmodo-flatuipro-rails#20]
I am integrating licensed version of flat-ui-pro with my Rails app.
For this, I am using 'designmodo-flatuipro-rails' gem

My environments are:-
OS - Windows7 32-bit
Ruby - 1.9.3p327
Rails - 4.0.0
twitter-bootstrap-rails - 2.2.8
jquery-ui-rails - 4.0.5
designmodo-flatuipro-rails - 1.1.4.2

I have generated "bootstrap_and_overrides.css" file by bootstrap generator at location "app/assets/stylesheets/". I am not using ".less" files for bootstrap.

I am also not getting Cannot detect twitter-bootstrap-rails install error
and Invalid Flat UI Pro directory error while running the flatUI generating command. It means I am inside the right FlatUI directory.

When I run the flat-ui-pro generate command `rails g flatuipro:install ./FlatUI/HTML/UI/Flat-UI-Pro-1.1.4`, It is throwing a error

```
Could not find "./FlatUI/HTML/UI/Flat-UI-Pro-1.1.4/css/flat-ui.css" in any of yo ur source paths. Your current source paths are: C:/Ruby193/lib/ruby/gems/1.9.1/gems/designmodo-flatuipro-rails-1.1.4.2/lib/gener ators/flatuipro/install/templates
```

I am getting the same error while passing the FlatUI directory containing PSD and HTML both.

I am not understanding why generator can not recognizing flat-ui.css in the right directory while it is available at this location.

I used differ version of `gem "designmodo-flatuipro-rails", "~> 1.2.2.0.branch`" with the other version of FlatUI-Pro directory (1.2.2) but also getting the same error.

Stackoverflow Question :- http://stackoverflow.com/questions/19563306/could-not-find-flat-ui-css-in-any-of-your-source-paths-while-generating-flat-u

Please provide any solution for fixing this.
Thanks.

**Comment by reflection** [comment]
Hi Rohit,

I don't have your exact setup, but following the steps for css in #4 everything worked perfectly for me.

``` bash
# Create new rails app 'lifeofpi'
mwg@ubuntu:~$ rails new lifeofpi

# Install jquery-ui-rails and twitter-bootstrap-rails
mwg@ubuntu:~/lifeofpi$ echo -e "gem 'jquery-ui-rails'\ngem 'twitter-bootstrap-rails'" >> Gemfile
mwg@ubuntu:~/lifeofpi$ bundle install
mwg@ubuntu:~/lifeofpi$ rails generate bootstrap:install static

# Install designmodo-flatuipro-rails
mwg@ubuntu:~/lifeofpi$ echo -e "gem 'designmodo-flatuipro-rails'" >> Gemfile
mwg@ubuntu:~/lifeofpi$ bundle install
mwg@ubuntu:~/lifeofpi$ rails generate flatuipro:install ~/Dropbox/Developer/flatuipro

# All done!
```

OS: Mac OS X Mavericks
Ruby 2.0.0
Rails 4

Since you're using the twitter-bootstrap-rails gem, you're using Bootstrap 2, so you wouldn't want to use the 1.2\* branch (which only applies for Bootstrap 3 and relies on a  different gem).  If you search through the issues, I think for whatever reason Windows users have problems... and I'm not sure how to fix since Windows is banned everywhere I am (work/home =).

Sam

**Comment by shangrila** [comment]
Same problem here, solution doesn't work.

**Comment by jehughes** [comment]
I'm not on Windows but I've created similar problems for myself by not having the HTML sub-directory directly under the path given to the generator.

What works for me is the less files, for example, are here:
<code>~/flat-ui-pro-1.2.2/HTML/UI/Flat-UI-Pro-1.2.2/less</code>

And the call to the generator is:
<code>rails generate flatuipro:install ~/flat-ui-pro-1.2.2</code>
