### ISSUE TITLE
Dropdown for touch events on iOS and and Android

### ISSUE THREAD

**Issue by saturday** [reflection/designmodo-flatuipro-rails#23]
If I precompile I get an issue on mobile with all touch events on dropdowns. They simply don't work. This is certainly a javascript issue.

I can't seem to find out what the issue it, and this might be a separate issue entirely. However, I can't check because I can't deploy without precompiling. The same issue can be found here:

reflection/designmodo-flatuipro-rails#22

There also seems to be similar problems with Heroku here:

reflection/designmodo-flatuipro-rails#10 - which was closed, but isn't necessarily best practice as the issue title implies. 

Here is a screenshot of the iOS emulator after an attempt to tap on the collapsed menu.

It simply gets dark on the tap, which suggests the touch event is firing; however nothing happens. It works locally as suggested above. I'm debugging via safari and the iphone simulator, and I'm not getting any ostensible errors.

![screen shot 2013-11-28 at 7 58 05 am](https://f.cloud.github.com/assets/669648/1639936/c92d43fc-582c-11e3-873f-88b55df175c1.png)

**Comment by saturday** [comment]
There's not much one can do here but precompile. It's a matter of a lot of trial and error, especially with Heroku, which becomes a tremendous pain in the bottom.

**Comment by jimjones26** [comment]
Did you ever figure this out? I am having an issue where Dropdowns are not working in Heroku, and I am at my wits end on trying to figure out the solution.
