### ISSUE TITLE
Support for Flat Ui Pro v1.3

### ISSUE THREAD

**Issue by rubydog** [reflection/designmodo-flatuipro-rails#28]
There are changes in directory structures for flat ui pro v1.3. Can you update the gem accordingly.

**Comment by reflection** [comment]
My plan is to have a new version ready this weekend.  Sorry for the delay.

**Comment by rubydog** [comment]
@reflection any chance its ready?

**Comment by dchbx** [comment]
+1

**Comment by reflection** [comment]
Quick update: Maybe 75% done... lots of little issues to iron out though.  You can see my progress on the flatuipro-1.3 branch.

**Comment by rubydog** [comment]
Super. Thanks for a wonderful gem :)

**Comment by reflection** [comment]
Gem released.
