### ISSUE TITLE
Less::ParseError - 'flat-ui.less' wasn't found.

### ISSUE THREAD

**Issue by ghost** [reflection/designmodo-flatuipro-rails#3]
After some debugging it turns out the rails.rb file was not loading and therefore the app.config.less.paths was not being updated to point at gems less dir.  I Moved 'lib/designmodo/flatuipro/rails.rb' to 'lib/designmodo-flatuipro-rails.rb' and everything works great.  Not sure why the change was needed.  Any comments or suggestions? 

Rails 3.2.9 and Ruby 1.9.2

**Comment by reflection** [comment]
Hi pigeonhouse,

I tried replicating your environment with rvm (installed Ruby 1.9.2 with Rails 3.2.9) and had no problems.  Glad you could fix it yourself, but it's definitely puzzling.

Also, probably a good idea to upgrade to Rails 3.2.13 for security patches.

**Comment by ghost** [comment]
Will do, thanks for the reply

**Comment by thejchap** [comment]
Interesting, I actually encountered the same issue. @pigeonhouse's fix worked.
