### ISSUE TITLE
Generator Supporting Free Version

### ISSUE THREAD

**Issue by fernandes** [reflection/designmodo-flatuipro-rails#34]
Hi @reflection,

You did a great job on this gem, really helpful.

My idea was support pro and free version on the same gem, what's your thoughts?

Guys at designmodo keeps two repos https://github.com/designmodo/Flat-UI and https://github.com/designmodo/Flat-UI-Pro with the same structure, so supporting would make life easier considering this repos

And instead the script I suggest below, we could use git clone the repos on designmodo

makes sense to you?

ps: People who uses rbenv usually run `bundle install --path vendor/bundle` so when gem copy the files to gem_assets_dir its usually ignore on .gitignore, so I wrote a [shell script](https://gist.github.com/fernandes/c2950cdb2bfc9c6c3604) to copy (only neede) pro files to vendor/flat_ui_pro so can run the generator on this folder.

**Comment by reflection** [comment]
@fernandes, feel free to fork my repo and make it work with the free version if you'd like (not a bad idea, btw =)  The goal of this gem is only to support the pro version.

**Comment by fernandes** [comment]
perfectly, thanks for the quick reply... again, thank you :)
