### ISSUE TITLE
The directory of the flat UI

### ISSUE THREAD

**Issue by nichthinkof30** [reflection/designmodo-flatuipro-rails#4]
I rename UI folder into flat-UI and located them under app/assets, when I tried to run 
rails g flatuipro:install ~/app/assets/flat-UI
and it is not working. What directory need to specify?

AppName

 -App

   -assets

```
  -flat-UI

    -bootstrap
    -css
    -fonts
    -images
    -js
    -less

  -images

  -javascripts

  -stylesheets
```

this is my tree view of directory

**Comment by reflection** [comment]
The gem doesn't detect correctly when you copy only the UI directory (see #2).  You'll need to copy the whole Flat UI Pro directory and point to that.

By the way, you don't have to copy Flat UI Pro into your rails app directory tree.

**Comment by nichthinkof30** [comment]
hmm, sorry I dont get it...it don't need to copy the directory of flat-ui into railsapp?? It will auto load into rails app after the command?
My path..
Desktop/Flat UI HTML - Personal License/HTML/UI

**Comment by nichthinkof30** [comment]
it that path name have to be exact?? @reflection

**Comment by reflection** [comment]
Hi Nicholas,

I'm sorry you're having issues.  Here's an install from scratch with comments that will hopefully help you understand what I meant.

``` bash
# RVM is so cool
mwg@ubuntu:~$ rvm gemset create rails-4.0
gemset created rails-4.0    => /usr/local/rvm/gems/ruby-2.0.0-p0@rails-4.0

mwg@ubuntu:~$ rvm use 2.0.0@rails-4.0
Using /usr/local/rvm/gems/ruby-2.0.0-p0 with gemset rails-4.0

mwg@ubuntu:~$ gem install rails
…
Installing ri documentation for rails-4.0.0
Done installing documentation for i18n, multi_json, tzinfo, minitest, atomic, thread_safe, activesupport, builder, rack, rack-test, erubis, actionpack, activemodel, arel, activerecord-deprecated_finders, activerecord, mime-types, polyglot, treetop, mail, actionmailer, thor, railties, hike, tilt, sprockets, sprockets-rails, rails (462 sec).
28 gems installed

# Create new rails app 'superbad'
mwg@ubuntu:~$ rails new superbad
      create  
…

# Install jquery-ui-rails and twitter-bootstrap-rails with LESS support
mwg@ubuntu:~$ cd superbad
mwg@ubuntu:~/superbad$ echo -e "gem 'jquery-ui-rails'\ngem 'twitter-bootstrap-rails'\ngem 'therubyracer'\ngem 'less-rails'" >> Gemfile
mwg@ubuntu:~/superbad$ bundle install
mwg@ubuntu:~/superbad$ rails generate bootstrap:install less

# Install designmodo-flatuipro-rails
# My FlatUIPro directory is just where I extracted the licensed zip to
mwg@ubuntu:~/superbad$ echo -e "gem 'designmodo-flatuipro-rails'" >> Gemfile
mwg@ubuntu:~/superbad$ bundle install
mwg@ubuntu:~/superbad$ rails generate flatuipro:install ~/Dropbox/Developer/flatuipro

# All done!
```

**Comment by nichthinkof30** [comment]
Hi @reflection, really thanks for your detail command, I want to ask is that "~/Dropbox/Developer/flatuipro" this path, must be necessary the same?? because when I download from the source given, the directory name was different.  I extract it on my Desktop, therefore my path was ~/Desktop/Flat UI HTML - Personal License/HTML/UI ?? But I tried this ,it gave me invalid directory as well.

**Comment by reflection** [comment]
Just the root directory of Flat UI Pro works for now (like I mentioned in #2).  So for you it would probably be something like:

``` bash
rails generate flatuipro:install "~/Desktop/Flat UI HTML - Personal License"
```

**Comment by nichthinkof30** [comment]
@reflection  Hi, I have no idea why it don't work on me...is that necessay to install less? I got the gem installed but used the static 1 as mentioned in the github.

**Comment by reflection** [comment]
Just for fun here's an even simpler from scratch install with static bootstrap assets (CSS instead of LESS).  Try these commands, and if they don't work for you, show me the errors/output.

``` bash
# Create new rails app 'lifeofpi'
mwg@ubuntu:~$ rails new lifeofpi

# Install jquery-ui-rails and twitter-bootstrap-rails
mwg@ubuntu:~/lifeofpi$ echo -e "gem 'jquery-ui-rails'\ngem 'twitter-bootstrap-rails'" >> Gemfile
mwg@ubuntu:~/lifeofpi$ bundle install
mwg@ubuntu:~/lifeofpi$ rails generate bootstrap:install static

# Install designmodo-flatuipro-rails
mwg@ubuntu:~/lifeofpi$ echo -e "gem 'designmodo-flatuipro-rails'" >> Gemfile
mwg@ubuntu:~/lifeofpi$ bundle install
mwg@ubuntu:~/lifeofpi$ rails generate flatuipro:install ~/Dropbox/Developer/flatuipro

# All done!
```

**Comment by nichthinkof30** [comment]
@reflection , I will figure out this later, thanks for your patient. If still got any problem, i will ping you again ...:D Thanks !

**Comment by nichthinkof30** [comment]
@reflection  Hi, I tried to create a plain new project, it still giving me invliad flat ui pro directory

copy_assets': Invalid Flat UI Pro directory (RuntimeError)
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in`each'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/invocation.rb:127:in`invoke_all'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/railties-4.0.0/lib/rails/generators.rb:156:in `invoke'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/railties-4.0.0/lib/rails/commands/generate.rb:11:in`<top (required)>'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in `require'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in`block in require'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:213:in `load_dependency'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/activesupport-4.0.0/lib/active_support/dependencies.rb:228:in`require'
    from /home/nicholas/.rvm/gems/ruby-2.0.0-rc2@rails4/gems/railties-4.0.0/lib/rails/commands.rb:49:in `<top (required)>'
    from bin/rails:4:in`require'
    from bin/rails:4:in `<main>'

**Comment by reflection** [comment]
Please include the command you ran to get that output.  

Are you sure you're pointing to the root ~/Desktop/Flat UI HTML - Personal License directory?

**Comment by nichthinkof30** [comment]
yup...I even tried the full path @@ @reflection , my app was on the Desktop too. 
App path:
/Desktop/myapp
Flat UI path:
/Desktop/Flat UI HTML - Personal License directory

**Comment by oschvr** [comment]
I am having the same issue.

os@os ~/D/o/flatui1.3.2.0 [1]> rails generate flatuipro:install ~/Desktop/Flat-UI-Pro-1.3.2/
/usr/local/lib/ruby/gems/2.2.0/gems/designmodo-flatuipro-rails-1.3.0.0.branch/lib/generators/flatuipro/install/install_generator.rb:22:in `copy_assets': Invalid Flat UI Pro directory (RuntimeError)
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in`run'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`block in invoke_all'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`map'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/group.rb:232:in`dispatch'
    from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/generators.rb:157:in`invoke'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/generate.rb:13:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in`require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:123:in`require_command!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:130:in `generate_or_destroy'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:50:in`generate'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /usr/local/lib/ruby/gems/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in`<top (required)>'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in`block in require'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in`require'
    from /Users/os/Desktop/oscarchavez/flatui1.3.2.0/bin/rails:8:in `<top (required)>'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in`load'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in`load_dependency'
    from /usr/local/lib/ruby/gems/2.2.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
    from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /usr/local/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from -e:1:in`<main>'
