### ISSUE TITLE
Cannot detect twitter-bootstrap-rails install (RuntimeError)

### ISSUE THREAD

**Issue by thejchap** [reflection/designmodo-flatuipro-rails#5]
Hi!

I keep getting this error on install:

> gems/designmodo-flatuipro-rails-1.1.1/lib/generators/flatuipro/install/install_generator.rb:107:in `use_less?': Cannot detect twitter-bootstrap-rails install (RuntimeError)
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/designmodo-flatuipro-rails-1.1.1/lib/generators/flatuipro/install/install_generator.rb:22:in`copy_assets'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/invocation.rb:120:in`invoke_command'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `block in invoke_all'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/invocation.rb:127:in`each'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/invocation.rb:127:in `map'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/invocation.rb:127:in`invoke_all'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/group.rb:233:in `dispatch'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/thor-0.18.1/lib/thor/base.rb:439:in`start'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/railties-3.2.13/lib/rails/generators.rb:171:in `invoke'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/railties-3.2.13/lib/rails/commands/generate.rb:12:in`<top (required)>'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in `require'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`block in require'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:236:in `load_dependency'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/activesupport-3.2.13/lib/active_support/dependencies.rb:251:in`require'
>     from /Users/Justin/.rvm/gems/ruby-2.0.0-p195@feedbackloop/gems/railties-3.2.13/lib/rails/commands.rb:29:in `<top (required)>'
>     from script/rails:6:in`require'
>     from script/rails:6:in `<main>'

Gemfile:

> gem 'designmodo-flatuipro-rails'
> gem "twitter-bootstrap-rails"
> gem "bootstrap-sass", ">= 2.2.2.0"
> gem 'sass-rails',   '~> 3.2.3'
> gem 'therubyracer'
> gem 'less-rails'
> gem 'jquery-ui-rails'

Any thoughts? I've tried moving them in/out of assets group in the gemfile, different Flat UI Pro directories (ie just the root vs /html)

**Comment by reflection** [comment]
Did you make sure to run the twitter-bootstrap-rails install generator first?

``` bash
# If you want LESS
rails generate bootstrap:install less

# Or CSS
rails generate bootstrap:install css
```

The code that's failing:

``` ruby
private
        # Detect if twitter-bootstrap-rails installed with LESS or static stylesheets
        def use_less?
          if File.exist?("app/assets/stylesheets/bootstrap_and_overrides.css.less")
            return true
          elsif File.exist?("app/assets/stylesheets/bootstrap_and_overrides.css")
            return false
          else
            raise "Cannot detect twitter-bootstrap-rails install"
          end
        end
```

If you renamed either of the files, that would cause a problem too.

**Comment by thejchap** [comment]
Got it!
I had run the generator without appending "less" (had been on scss before)

All is well. Thanks!
