### ISSUE TITLE
Javascript not loading?

### ISSUE THREAD

**Issue by mattdanna** [reflection/designmodo-flatuipro-rails#6]
It doesnt appear like some javascript files are loading from the gem. When creating a rails app following [your instructions explicitly](https://github.com/reflection/designmodo-flatuipro-rails/issues/4#issuecomment-20027450), and copying the Flat-UI-Pro's template.html into the app, lots of styles get messed up:
![image](https://f.cloud.github.com/assets/1121110/725459/c0b0a370-e06a-11e2-992d-a2dabac28495.png)
![image](https://f.cloud.github.com/assets/1121110/725462/010afc22-e06b-11e2-9c28-878def981ef0.png)

I didn't change any of the .less files in the ui kit.
Here's a zipped copy of my rails project in case it helps:
http://file.mdanna.me/0P0n3I1h2C1S

**Comment by reflection** [comment]
Hi Matt,

You are correct.  The template javascript isn't loaded by default.  For your example to work, make sure the javascript section of the original template in the Flat UI Pro pack is included (js/application.js).  Please note that the javascript in there is really just for the template itself, and you should customize it for your needs in your app.

The gem (correctly, in my opinion) only includes the non-template specific javascript (basically everything else).

**Comment by nichthinkof30** [comment]
Hi @reflection ,
I'm facing the same problem. I see everything in the browser is loaded with all the js, and in my rails, i do include 

<%= stylesheet_link_tag 'application' %>
<%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>

I guess it should be everything loaded properly?

**Comment by jehughes** [comment]
I wrote up how I got the Flat UI Pro sample page running ... maybe there's something I did that will help? http://joanswork.com/add-flat-ui-pro-to-rails/

**Comment by nichthinkof30** [comment]
work like charm ! Thanks...it need to copy the application js content to the rails project Thanks @jehughes
