### ISSUE TITLE
I Have troubles installing Twitter Bootstrap with Less on Windows

### ISSUE THREAD

**Issue by Theminijohn** [reflection/designmodo-flatuipro-rails#9]
I'm getting a LOT of problem with the rubyracer gem and LibV8. Can i user Flatui pro with  Bootstrap Sass ?

**Comment by reflection** [comment]
Hi Theminijohn,

Sorry to hear that.  I develop on Ubuntu and Mac OS X, so I can't really help you troubleshoot why those gems aren't working.

You can certainly use SASS, but you'll have to translate the Flat UI Pro LESS -> SASS (along with Bootstrap's LESS -> SASS).
